### ISSUE TITLE
Examples don't work 400 and 422 returned

### ISSUE THREAD

**Issue by ggreenblat** [SparkPost/java-sparkpost#27]
Hi,

 Neither the basic not the template example from the README.md works. I get a 400 error on the basic example and 422 on the template example. There is no detail provided as to why I get the errors. A simple curl sample works though. I have setup an API key.

I also added the template ID to the example for templates in the README.md but still get a 422

{
  "recipients": [
    {
      "address": {
        "email": "somemail@gmail.com"
      }
    }
  ],
  "substitution_data": {
    "from": "noreply@domain.com"
  },
  "return_path": "noreply@domain.com",
  "content": {
    "template_id": "my-first-email",
    "email_rfc822": "testing an email here"
  }
}

**Comment by yepher** [comment]
You should use either `template_id` or `email_rfc822` and not both.

Also does your template and email_rfc822 have `from: {from}` in them. This example is replacing the from address with substitution data. I think this part is probably confusion in the example so I will update that.

If you want help debugging this real-time you can find me in our Slack channel here: http://slack.sparkpost.com

**Comment by yepher** [comment]
Created Issue #28 to improve logging when an error does occur

**Comment by yepher** [comment]
I will improve README but changing example to use text/html instead of template.

```

**Comment by yepher** [comment]
@ggreenblat,

I believe I've addressed most of what you are seeing. I am not quite sure why you are having an issue with the basic example. The changes in the upcoming v0.14 library will show you more error information that will help debug that more.

My hunch is your `from` domain is not the one you verified in SparkPost. Is the above  the exact JSON from request or did you change the from address to `"from": "noreply@domain.com"` to protect your actual address?

**Comment by ggreenblat** [comment]
Thank you for the great support and feedback. 

When I removed the  email rfc and used just the template id it worked.

It was not clear to me what email_rfc was. I assumed that it was a template cause of the substitution data.

Still not sure why I get a 400 on the basic request but there must be something small I a missing. I am using the correct domain and the example I posted I substituted the domain for privacy reasons. 

Extra debug info would be great. Thanks!

**Comment by yepher** [comment]
@ggreenblat 

Can you try the new version of the library I released yesterday? It is 0.14.

With the new library you will get the error JSON from the server which is usually pretty good about saying why it sent back the error.

I will do some testing of that example today and see if I can figure out a way to reproduce the problem.

**Comment by ggreenblat** [comment]
The additional error messages really help. The basic send now works. The reason it didn't was because of whitespace around the send to address. The error messages made that clear immediately.

**Comment by yepher** [comment]
Great, glad to hear it helped. Let me know if you have any other problems. You can reach out to me on Slack if you need to. 

You can join the community here: http://slack.sparkpost.com
